version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kubertest
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=verystrongpassword
      - POSTGRES_HOST=testdb
      - POSTGRES_PORT=5432
  web:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    restart: always
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ../src:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=kubertest
      - DATABASE_USERNAME=postgresuser
      - DATABASE_PASSWORD=verystrongpassword
      - DATABASE_HOST=testdb
      - DATABASE_PORT=5432
      - SECRET_KEY=secretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db